CREATE TABLE `tabCNCData` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` int(1) NOT NULL DEFAULT 0,
  `idx` int(8) NOT NULL DEFAULT 0,
  `_user_tags` text DEFAULT NULL,
  `_comments` text DEFAULT NULL,
  `_assign` text DEFAULT NULL,
  `_liked_by` text DEFAULT NULL,
  `equipmentid` varchar(140) DEFAULT NULL,
  `workpiececount` int(11) NOT NULL DEFAULT 0,
  `runtime` varchar(140) DEFAULT NULL,
  `cuttingtime` varchar(140) DEFAULT NULL,
  `cncmodel` varchar(140) DEFAULT NULL,
  `currenttoolno` varchar(140) DEFAULT NULL,
  `operationmode` varchar(140) DEFAULT NULL,
  `runmode` varchar(140) DEFAULT NULL,
  `rapidoverride` varchar(140) DEFAULT NULL,
  `spindleactualrpm` varchar(140) DEFAULT NULL,
  `feedactualrate` varchar(140) DEFAULT NULL,
  `spindleload` varchar(140) DEFAULT NULL,
  `xaxisload` varchar(140) DEFAULT NULL,
  `yaxisload` varchar(140) DEFAULT NULL,
  `zaxisload` varchar(140) DEFAULT NULL,
  `alarmcode` varchar(140) DEFAULT NULL,
  `alarmmessage` varchar(140) DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `modified` (`modified`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC
