CREATE TABLE `tabMESProductionData` (
  `name` varchar(140) NOT NULL,
  `creation` datetime(6) DEFAULT NULL,
  `modified` datetime(6) DEFAULT NULL,
  `modified_by` varchar(140) DEFAULT NULL,
  `owner` varchar(140) DEFAULT NULL,
  `docstatus` int(1) NOT NULL DEFAULT 0,
  `idx` int(8) NOT NULL DEFAULT 0,
  `_user_tags` text DEFAULT NULL,
  `_comments` text DEFAULT NULL,
  `_assign` text DEFAULT NULL,
  `_liked_by` text DEFAULT NULL,
  `workorderid` varchar(140) DEFAULT NULL,
  `equipmentid` varchar(140) DEFAULT NULL,
  `productid` varchar(140) DEFAULT NULL,
  `productname` varchar(140) DEFAULT NULL,
  `plannedquantity` varchar(140) DEFAULT NULL,
  `actualquantity` varchar(140) DEFAULT NULL,
  `starttime` varchar(140) DEFAULT NULL,
  `endtime` varchar(140) DEFAULT NULL,
  `operatorid` varchar(140) DEFAULT NULL,
  PRIMARY KEY (`name`),
  KEY `modified` (`modified`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC
